name: Automake CI

on:
  push:
    branches: [ "branchAutomake" ]
  pull_request:
    branches: [ "branchAutomake" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: sudo apt-get install -y automake autoconf

      - name: Build
        run: |
          aclocal
          automake --add-missing
          autoconf
          ./configure
          make
          make dist
