name: Debian Package CI

on:
  push:
    branches: [ "branchAutoPackage" ]
  pull_request:
    branches: [ "branchAutoPackage" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: sudo apt-get install -y debhelper devscripts

      - name: Build package
        run: |
          mkdir -p debian
          echo "Package: program" > debian/control
          echo "Version: 0.1" >> debian/control
          echo "Architecture: any" >> debian/control
          echo "Maintainer: Your Name <foxira242@gmail.com>" >> debian/control
          echo "Description: A sample C++ program" >> debian/control
          debuild -us -uc
