name: Test CI

on:
  push:
    branches: [ "branchAutoTest" ]
  pull_request:
    branches: [ "branchAutoTest" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: sudo apt-get install -y build-essential

      - name: Build
        run: |
          aclocal
          automake --add-missing
          autoconf
          ./configure
          make

      - name: Run tests
        run: ./main_test
